import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from jinja2 import Template
import base64

# -----------------------------
# Enhanced HTML Template
# -----------------------------
HTML_TEMPLATE = """
<html>
<head>
<title>StomaScope Batch Report</title>
<style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background-color: #f5f5f5; color: #333; }
    header { display: flex; align-items: center; border-bottom: 2px solid #28A745; padding-bottom: 20px; margin-bottom: 30px; }
    header img { height: 60px; margin-right: 20px; }
    h1 { color: #1E1E1E; margin: 0; }
    h2 { border-left: 5px solid #28A745; padding-left: 15px; margin-top: 50px; color: #2D2D2D; }
    h3 { color: #555; margin-top: 30px; }
    .card { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 30px; }
    .plot-grid { display: flex; flex-wrap: wrap; gap: 20px; }
    .plot-item { flex: 1 1 400px; text-align: center; }
    .metric-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    .metric-table th, .metric-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    .metric-table th { background-color: #f2f2f2; }
    footer { margin-top: 50px; font-size: 0.8em; color: #888; text-align: center; }
</style>
</head>
<body>

<header>
    {% if logo_base64 %}<img src="data:image/x-icon;base64,{{ logo_base64 }}" alt="Logo">{% endif %}
    <h1>StomaScope Analysis Report</h1>
</header>

<div class="card">
    <h2>Global Aggregate Analysis</h2>
    <div class="plot-grid">
        {% for metric, svg in boxplots.items() %}
        <div class="plot-item">
            <h3>{{ metric.replace("_"," ").title() }}</h3>
            {{ svg|safe }}
        </div>
        {% endfor %}
    </div>
</div>

<div class="card">
    <h2>Spatial Overview</h2>
    <div style="text-align: center;">
        {{ spatial_scatter|safe }}
    </div>
</div>

{% for group_name, leaves in per_group_data.items() %}
    <section class="group-section">
        <h2>Group: {{ group_name }}</h2>
        {% for leaf_id, plots in leaves.items() %}
            <div class="card">
                <h3>Leaf ID: {{ leaf_id }}</h3>
                <div class="plot-grid">
                    {% for plot_name, plot_svg in plots.items() %}
                    <div class="plot-item">
                        <p><strong>{{ plot_name }}</strong></p>
                        {{ plot_svg|safe }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </section>
{% endfor %}

<footer>
    <p>Generated by StomaScope v0.2.1 | {{ timestamp }}</p>
</footer>
</body>
</html>
"""

def write_html_report(grouped_stats, outdir, generate_csv=True, keep_svgs=False, log_file=None):
    os.makedirs(outdir, exist_ok=True)
    import datetime
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 1. Embed Logo (Keeping your existing logic)
    logo_base64 = ""
    logo_path = os.path.join(os.path.dirname(__file__), "..", "assets", "stomaScope.ico")
    if os.path.exists(logo_path):
        with open(logo_path, "rb") as f:
            logo_base64 = base64.b64encode(f.read()).decode("utf-8")

    per_group_data = {}
    
    # NEW: We now store data keyed by Group Name for the aggregate plots
    # Structure: { metric: { group_name: [combined_values] } }
    group_aggregate_data = {
        "area_um2": {}, 
        "aspect_ratio": {}, 
        "eccentricity": {}, 
        "circularity": {}
    }
    
    cmap = plt.cm.get_cmap("tab10")

    # 2. Process Data and Concatenate for Groups
    for g_idx, (group_name, items) in enumerate(grouped_stats.items()):
        per_group_data[group_name] = {}
        
        # Initialize the group arrays for each metric
        for metric in group_aggregate_data.keys():
            group_aggregate_data[metric][group_name] = []

        for leaf_id, stats in items:
            df = stats.get("features_df")
            if df is None or df.empty: continue
            
            if generate_csv:
                df.to_csv(os.path.join(outdir, f"{leaf_id}_features.csv"), index=False)

            # --- AGGREGATION LOGIC ---
            for metric in group_aggregate_data.keys():
                if metric in df.columns:
                    # We extend the group list with this leaf's values
                    values = df[metric].dropna().values
                    group_aggregate_data[metric][group_name].extend(values)

            # (Optional) Still generate individual leaf plots for the "Detailed" section
            plots = {}
            hist_path = os.path.join(outdir, f"temp_{leaf_id}_hist.svg")
            fig, ax = plt.subplots(figsize=(4, 3))
            ax.hist(df["area_um2"], bins=15, color=cmap(g_idx % 10), alpha=0.7)
            ax.set_title(f"Area Hist: {leaf_id}")
            fig.tight_layout()
            fig.savefig(hist_path, format="svg")
            plt.close(fig)
            plots["Area Histogram"] = embed_svg(hist_path)
            if not keep_svgs: os.remove(hist_path)
            per_group_data[group_name][leaf_id] = plots

    # 3. Create Group-Level Boxplots
    aggregate_boxplots = {}
    for metric, groups_dict in group_aggregate_data.items():
        # labels = ['Group 1', 'Group 2', ...]
        # plot_data = [ [vals1], [vals2], ... ]
        group_names = list(groups_dict.keys())
        plot_data = [groups_dict[name] for name in group_names if len(groups_dict[name]) > 0]
        active_labels = [name for name in group_names if len(groups_dict[name]) > 0]

        if not plot_data: continue

        fig, ax = plt.subplots(figsize=(max(6, len(active_labels)*1.5), 5))
        bp = ax.boxplot(plot_data, labels=active_labels, patch_artist=True)
        
        # Color each box by its specific group index
        for i, patch in enumerate(bp['boxes']):
            patch.set_facecolor(cmap(i % 10))
            patch.set_alpha(0.6)

        ax.set_ylabel(metric.replace("_", " ").title())
        ax.set_title(f"Group Comparison: {metric.replace('_', ' ').title()}")
        plt.xticks(rotation=15)
        fig.tight_layout()
        
        path = os.path.join(outdir, f"temp_group_agg_{metric}.svg")
        fig.savefig(path, format="svg")
        plt.close(fig)
        aggregate_boxplots[metric] = embed_svg(path)
        if not keep_svgs: os.remove(path)

    # 4. Global Spatial Scatter (Keeping your fixed logic)
    fig, ax = plt.subplots(figsize=(8, 6))
    for g_idx, (group_name, items) in enumerate(grouped_stats.items()):
        first_in_group = True
        for leaf_id, stats in items:
            df = stats.get("features_df")
            if df is not None and "centroid_x_um" in df.columns:
                ax.scatter(
                    df["centroid_x_um"], df["centroid_y_um"],
                    s=10, alpha=0.4, color=cmap(g_idx % 10),
                    label=group_name if first_in_group else ""
                )
                first_in_group = False
    
    ax.set_aspect("equal")
    ax.set_title("Global Spatial Distribution (By Group)")
    ax.legend(loc='upper right', title="Groups")
    fig.tight_layout()
    spatial_path = os.path.join(outdir, "temp_spatial.svg")
    fig.savefig(spatial_path, format="svg")
    plt.close(fig)
    spatial_svg = embed_svg(spatial_path)
    if not keep_svgs: os.remove(spatial_path)

    # 5. Render HTML (Same as before)
    html_content = Template(HTML_TEMPLATE).render(
        boxplots=aggregate_boxplots,
        per_group_data=per_group_data,
        spatial_scatter=spatial_svg,
        logo_base64=logo_base64,
        timestamp=timestamp
    )

    report_file = os.path.join(outdir, "StomaScope_Report.html")
    with open(report_file, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    return report_file

def embed_svg(svg_path):
    if not svg_path or not os.path.exists(svg_path): return ""
    with open(svg_path, "r", encoding="utf-8") as f:
        return f.read()